---
mqtt:
  broker: tcp://mosquitto.internal.k8s.vogelherdweg.de:1883

automate:
  lcn/segment/0/target/4/:
    - match: 
        $yaml: | 
          Src: 34
          Cmd: 104
          Payload: "MAQ="
      actions:
      - topic: shellyplusplugs-kaffeelicht/command/switch:0
        content: 
          $plain: on
      - topic: shellyplusplugs-spühle/command/switch:0
        content: 
          $plain: on
    - match: 
        $yaml: | 
          Src: 34
          Cmd: 104
          Payload: "MAA="
      actions:
      - topic: shellyplusplugs-kaffeelicht/command/switch:0
        content: 
          $plain: off
      - topic: shellyplusplugs-spühle/command/switch:0
        content: 
          $plain: off

logger:
  development: true
  disableCaller: false
  disableStacktrace: false
  encoding: console
  level: info

